# Generated by Django 5.0.6 on 2025-03-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='avaliacao',
            new_name='reviewText',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='estrelas',
            new_name='stars',
        ),
    ]
