# Generated by Django 5.0.6 on 2025-03-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_nome_review_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
